### ISSUE TITLE
pyfftw dependency

### ISSUE THREAD

**Issue by suberlak** [dwkim78/upsilon#2]
When installing your package I needed to do both 

> brew install fftw

and then 

> pip install pyfftw 

Otherwise it would keep asking for 
`/private/var/folders/y_/cnss5hqs3nz9dv_dd28yzt040000gn/T/pip-build-rfotlhg7/pyfftw/pyfftw/pyfftw.c:272:10: fatal error: 'fftw3.h' file not found
    #include "fftw3.h"
             ^
    1 warning and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1`

I suggest adding information about fftw to your docs, I spent some time trying to make it work.

**Comment by dwkim78** [comment]
README.md already mentions "You will need to install FFTW as well prior to installation of pyFFTW.". It is up to users how to install FFTW because install procedure of FFTW could be different for different OS (e.g. linux, mac, windows).

Cheers,
