### ISSUE TITLE
test_predict() unable to load RFC from old scikit

### ISSUE THREAD

**Issue by suberlak** [dwkim78/upsilon#3]
When running the 
> upsilon.test_predict()

I get  the error which ends with : 

/Users/chris/anaconda3/lib/python3.5/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-4-66e47bad2645> in <module>()
----> 1 u.test_predict()

/Users/chris/anaconda3/lib/python3.5/site-packages/upsilon/test/predict.py in run()
     52 
     53    logger.info('Load the UPSILoN classifier')
---> 54    rf_model = load_rf_model()
     55 
     56    logger.info('Classify the light curve')

/Users/chris/anaconda3/lib/python3.5/site-packages/upsilon/datasets/base.py in load_rf_model()
     60    module_path = dirname(__file__)
     61    file_path = join(module_path, 'models/rf.model.sub.github.gz')
---> 62    clf = pickle.load(gzip.open(file_path, 'rb'))
     63 
     64    return clf

UnicodeDecodeError: 'ascii' codec can't decode byte 0xfe in position 2208: ordinal not in range(128)

I traced it down to line 62 in upsilon/datasets/base.py   , 

and when I changed it to 

>> clf = pickle.load(gzip.open(file_path, 'rb’), encoding=‘latin1')

I get a more informative error : 

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-26-21de25074591> in <module>()
----> 1 clf = pickle.load(gzip.open(file_path, 'rb'), encoding='latin1')

sklearn/tree/_tree.pyx in sklearn.tree._tree.Tree.__setstate__ (sklearn/tree/_tree.c:8128)()

KeyError: 'max_depth'

Which points me in a direction that your models were made with old scikit learn, so that anyone trying to test the installation will find it to fail with the most up-to-date installation of python and scikit learn.  Can you fix this issue ? 

Thank you
Chris

**Comment by suberlak** [comment]
see https://github.com/scikit-learn/scikit-learn/issues/7826

**Comment by dwkim78** [comment]
You're using Python 3 while the upsilon supports only Python 2 (read the "Dependency" section at README.md). If you're in hurry, please use: "https://github.com/dwkim78/py3-upsilon", which is an identical package but supporting Python 3. I'll integrated them sometime in the near future.

Cheers,

Dae-Won
