### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mirsakhawathossain** [dwkim78/upsilon#5]
I have not understood the processes clearly how to use this library for my observation database or other databases. Could you please help me? If you can I will write the documentation myself and it will clarify the uses.

**Comment by dwkim78** [comment]
The UPSILoN document already gives very details about how to run it in Python. Could you explain which part you don't understand?

**Comment by mirsakhawathossain** [comment]
I didn't understand isalias function. Could you please explain? I am going to use this library for variable star candidate.

**Comment by mirsakhawathossain** [comment]
How many observation data is needed to classify variable stars?

**Comment by dwkim78** [comment]
Please read the papers mentioned in the UPSLIoN document: 
- Kim & Bailer-Jones 2015 (https://arxiv.org/abs/1512.01611)
- Kim et al. 2014 (http://adsabs.harvard.edu/abs/2014A%26A...566A..43K)

All your questions are already answered in either the UPSILoN document or the paper.
