### ISSUE TITLE
Upgrade tree model to latest scikit-learn

### ISSUE THREAD

**Issue by mrosseel** [dwkim78/upsilon#6]
When running upsilon, scikit-learn warns that the model is saved by an old version:
```
/opt/conda/lib/python3.6/site-packages/sklearn/base.py:251: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.18.1 when using version 0.20.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
```

Alternatively, would it be possible to release the train/test sets on which this model was trained? (not only for the model warning but also for possible deep learning improvements)

**Comment by dwkim78** [comment]
Hi, 

I'm working on training deep learning models to see if there is any improvement. I hope that I could release it sometime in the near future.

Cheers,

**Comment by dwkim78** [comment]
The Model is updated accordingly to scikit-learn 0.21.3
