### ISSUE TITLE
No longer works with newer versions of scikit-learn and outdated upstream

### ISSUE THREAD

**Issue by rayment** [dwkim78/upsilon#9]
scikit-learn has received [an update](https://github.com/scikit-learn/scikit-learn/commit/437ca0553ce8d97571cecc3f4df8493e5cf959c5) which has renamed `sklearn.ensemble.forest` to `sklearn.ensemble._forest` thus no models can be loaded. `sklearn.trees.trees` was also renamed to `sklearn.trees._trees`.

`ModuleNotFoundError: No module named 'sklearn.ensemble.forest'` is the error that is shown when pickle tries to load the gz file.

To fix this, an older version of scikit-learn can be installed such as 0.21.3 to solve the issue:
`pip install -U scikit-learn==0.21.3`

Take note that pips upstream is still broken for python3 as the latest commit in 2020 fixing the library hasn't been added yet.

For now, installing the library with `pip install git+https://github.com/dwkim78/upsilon` will solve the issue.

**Comment by dwkim78** [comment]
Updated to sklearn 0.24.1
